- Helm/opensearch/templates/networkpolicy.yaml
This fixes the problem of installing this chart multiple times in the
same namespace and having the network policy name conflict.
n/a
> Give networkpolicy objects a unique name

- Helm/opensearch/templates/statefulset.yaml
- Helm/opensearch/values.yaml
Using :latest by default is going to lead to clusters with version skew
as pods schedule onto new nodes. So use a stable tag instead.
n/a
> Use the stable chart appVersion as image tag by default

- Helm/opensearch/values.yaml
I know it is only a demo configuration, but having a setting that is definitely not correct for a kubernetes statefulset confused me.
Closes: #22
> Update demo config

- Helm/opensearch/templates/statefulset.yaml
Signed-off-by: johannes.reppin <johannes.reppin@desy.de>
configSecret Volumes are added in Pod Spec and YAML indentaion is fixed, otherwise Helm does not render (!)
#26 
- [X ] Commits are signed per the DCO using --signoff 
> add configSecret Volumes

- Helm/opensearch-dashboards/templates/ingress.yaml
The ingress `apiVersion: networking.k8s.io/v1` is available in kubernetes 1.19 and is the only valid version in kubernetes 1.22+.
You may also want to do a similar patch for `Helm/opensearch/templates/ingress.yaml`.
> support for current ingress apiVersion

- Helm/opensearch-dashboards/templates/deployment.yaml
- Helm/opensearch-dashboards/values.yaml
The manifests rendered by the Helm chart place the user provided config
into the incorrect directory. This simply updates that location to the
correct path and updates the values.yaml file to use the correct default
config file so that the user provided setting override the defaults.
Signed-off-by: Harrison Goscenski <harrison.goscenski@imanage.com>
Resolves issue #37 
#37 
> Fixing config path in opensearch-dashboards

- Helm/opensearch-dashboards/values.yaml
After switching the name of the config file, and removing the shadowing
between the default (from the docker container opensearch-dashbaords.yaml) and the default from the helm chart (dashboards.yaml) there is an issue with the certs that are attempting to be used.
In order for this to work with the defaults, disabled TLS verification
will be needed, and then disabling TLS to remain in line with the
defaults.
I added a commented out section showing what could potentially be used
as TLS config if the user chooses to enable it.
Signed-off-by: Harrison Goscenski <harrison.goscenski@imanage.com>
[Describe what this change achieves]
#55
For more information on following Developer …
> Fix helm chart can not be deployed without ssl

- MAINTAINERS.md
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Add TheAlgo and DandyDeveloper as the new maintainers of the repo
[List any issues this PR will resolve]
> Add TheAlgo and DandyDeveloper as the new maintainers of the repo

- .github/workflows/nightly-playground-test.yml
- nightly-playground/.eslintrc.js
- nightly-playground/.gitignore
- nightly-playground/.npmignore
- nightly-playground/README.md
- nightly-playground/bin/nightly-playground.ts
- nightly-playground/cdk.json
- nightly-playground/jest.config.js
- nightly-playground/lib/nightly-playground-stack.ts
- nightly-playground/package-lock.json
- nightly-playground/package.json
- nightly-playground/test/nightly-playground.test.ts
- nightly-playground/tsconfig.json
This change adds the initial draft of nightly playgrounds with below specifics:
1. distribution version, distribution urls are grabbed on the go whereas all other important parameters are hardcoded in the code
2. Adds tests
3. Adds GHA workflow to run tests
#129 
> Add nightly playground

- .github/workflows/deploy-nightly-playground.yml
- .github/workflows/index-data.yml
- nightly-playground/lib/common-tools-stack.ts
- nightly-playground/lib/nightly-playground-stack.ts
- nightly-playground/package-lock.json
- nightly-playground/package.json
- nightly-playground/test/nightly-playground.test.ts
This PR includes below changes:
1. Bumps opensearch-cluster-cdk version to 1.2.0
2. Adds commons stack that is responsible for adding route53 and certificate 
3. Adds tests to test above resources
4. Changes opensearch and opensearch Dashboards port mapping on load balancer
> Add commons Stack with DNS and certificate

- nightly-playground/lib/nightly-playground-stack.ts
- nightly-playground/package-lock.json
- nightly-playground/package.json
- nightly-playground/test/nightly-playground.test.ts
Since we are using external certificate for nightly playground (ACM) in this case based on the domain name, this change adds the additional config for opensearch-dashboards. 
```
"opensearch_security.cookie.secure": "true"
"opensearch_security.cookie.isSameSite": "None"
```
#129 
> Add dashboards config for external cert

- .github/workflows/deploy-nightly-playground.yml
Now that we know nightly playground works well, moving the deployment from 2.11.0 to 2.13.0
#129 
> Deploy 2.13.0

- .github/workflows/nightly-playground-deploy.yml
- .github/workflows/nightly-playground-trigger.yml
With the workflow trigger being changed from workflow_dispatch to workflow_call, the workflow needs additional permissions `secrets: inherit` in this case to assume the credentials. 
Also updates the permissions for ngnix stack and fixes context variable name
related to #129 
> Fix context variable name and workflow permissions

- .github/workflows/nightly-playground-deploy.yml
Making NLB instance accessible at stack level changed the outputs array. This PR fixes it.
Also removes output.json which is not being used.
> Fix output array for getting endpoint

- nightly-playground/lib/common-tools-stack.ts
- nightly-playground/lib/nightly-playground-stack.ts
- nightly-playground/test/nightly-playground.test.ts
- Add snapshot S3 bucket that will be used to store cluster snapshots and restore relevant indices from other snapshots
- Also adds custom role with additional permissions for S3 bucket. Separating the role from the default one gave us more control on the type of policy and permissions we might want to add in future too.
> Add snapshot S3 bucket and custome role

- .github/workflows/nightly-playground-deploy.yml
This PR adds an additional job in the workflow to register a snapshot repository within the cluster with `versionX` as base path.
Also fixes the cdk_vars typo due to which the GH output was not being set
Adds `-f` flag to the curl command to fail fast
https://github.com/opensearch-project/opensearch-devops/issues/132
> Enable snapshot repo registration and fix cdk_vars

- .github/workflows/nightly-playground-trigger.yml
After checking the validation for 2.14.0 https://build.ci.opensearch.org/job/distribution-validation/406/console its finally time to move on to 2.14.0 release for 2x endpoint
> Bump 2x plyaground to 2.14.0

- .github/workflows/nightly-playground-deploy.yml
We have manually added monitors for below:
- Red cluster
- High JVM
- Node drop
This PR will keep restoring those config into newly deployed clusters by reindexing `.opendistro-alerting-config,.opensearch-notifications-config` back to the cluster. 
#132 
> Enable restoring alerting config from snapshots

- .github/workflows/nightly-playground-trigger.yml
As of now, if one of the version fails to deploy the other fails to deploy as well. Setting fail fast to false allows to decouple both the deployments. Example workflow run: https://github.com/gaiksaya/opensearch-devops/actions/runs/8767748504/job/24061359684
> Set fail-fast to false for nightly deployments

- .github/workflows/nightly-playground-deploy.yml
- nightly-playground/resources/monitors-config/cluster_health_monitor.json
- nightly-playground/resources/monitors-config/jvm_monitor.json
- nightly-playground/resources/monitors-config/node_monitor.json
since `.opendistro-alerting-config,.opensearch-notifications-config` are system level indices we am unable to restore them using snapshot as they are protected by [security permissions](https://opensearch.org/docs/latest/security/configuration/system-indices/). Instead of removing protection, we are configuring monitors and notification channel using REST APIs. The config files include monitor config for 
- Red cluster
- High JVM
- Node drop
closes #132 
> Configure notifications and alerts using curl

- .github/workflows/nightly-playground-deploy.yml
- nightly-playground/lib/nightly-playground-stack.ts
- nightly-playground/lib/waf.ts
- nightly-playground/test/nightly-playground.test.ts
As per WAF documentation, only following formats are supported 
```
* - For an Application Load Balancer: `arn:aws:elasticloadbalancing: *region* : *account-id* :loadbalancer/app/ *load-balancer-name* / *load-balancer-id*`
* - For an Amazon API Gateway REST API: `arn:aws:apigateway: *region* ::/restapis/ *api-id* /stages/ *stage-name*`
* - For an AWS AppSync GraphQL API: `arn:aws:appsync: *region* : *account-id* :apis/ *GraphQLApiId*`
```
Since this clusters use NLB need to come up with another solution
* Also only deploys infraStack using workflow. Since 2x and 3x runs simultaneously, the cloudformation status check fails the stack update saying `CREATE_IN_PROGRESS state and can not be updated` See https://github.com/opensearch-project/opensearch-devops/actions/runs/8902202666/job/2444769 …
> Disable WAF for NLB and only deploy infraStack

- .github/workflows/nightly-playground-deploy.yml
For runs that do not actually update the stack, the deployment still shows successful moving to next step.While indexing and adding sample data works, adding an already existing channel throws [409](https://github.com/opensearch-project/opensearch-devops/actions/runs/8913867098/job/24480310602)
This PR adds check and only adds the channel if it is missing
#132 
> Add a check for existing notification channel

- nightly-playground/lib/routing.ts
- nightly-playground/test/nightly-playground.test.ts
For some reason (or by design) the aws cdk writes the file first and the executes the shell commands no matter what. Since ngnix is installed after writing the file to `/usr/share/nginx/html/index.html` the package overwrites it with default one during execution. However, for non-default files like `/etc/nginx/conf.d/opensearchdashboard.conf` and `/usr/share/nginx/html/index_nightly.html`, are retained. Hence modifying the implementation a to accommodate this behavior 
For more information on following Developer Certificate of Origin and signing off your commits, please check …
> Fix homepage for nightly

- keycloak/bin/keycloak.ts
- keycloak/lib/stacks/keycloak.ts
Fix path and remove env. env is causing issues with cdk synth.
> Fix path and remove env

- .github/workflows/nightly-playground-trigger.yml
Bump nightly playgrounds to 2.17
https://github.com/opensearch-project/opensearch-build/issues/4908
> Bump nightly playgrounds to 2.17

- nightly-playground/DEVELOPER_GUIDE.md
- nightly-playground/README.md
Add documentation and developer guide for nightly playgrounds
> Add documentation and developer guide

- .github/workflows/nightly-playground-trigger.yml
- nightly-playground/resources/security-config/roles_mapping.yml
- nightly-playground/test/nightly-playground.test.ts
Created a new backend role in keycloak `admin_role_for_nightly` where users will have admin access. 
For all other user, `default-roles-opensearch-nightly-playgrounds` is default role via keycloak. Mapping it to readonly users.
Also bump version to 2.18
> Map users by default to read-only role and add another one for admin

- keycloak/README.md
- keycloak/resources/docker-compose.yml
- keycloak/resources/internal-docker-compose.yml
Upgrade keycloak to 26.0.0. Also updates readme. 
> Upgrade keycloak to 26.0.0

- .github/workflows/nightly-playground-trigger.yml
Bump version to 3.0 GA as beta1 is out now. 
> Bump version to 3.0 GA

- .github/workflows/nightly-playground-trigger.yml
Bump nightly playgrounds version to upcoming 2.19.3 and 3.1.0
> Bump nightly playgrounds version

- nightly-playground/package-lock.json
- nightly-playground/package.json
Upgrade cluster cdk to 1.4.0 that comes with few dependency bumps and few new features. 
> Upgrade cluster cdk to 1.4.0
