opensearch-project/opensearch-devops

- .github/ISSUE_TEMPLATE/bug_template.md
- .github/ISSUE_TEMPLATE/feature_request.md
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Add issue templates to this DevOps Repository
> Add issue templates to this DevOps Repository

- Helm/opensearch-dashboards/values.yaml
add secretMounts to values.yaml
fixes #28 
> Add secret mounts to values

- Helm/opensearch/templates/statefulset.yaml
- Helm/opensearch/values.yaml
merge volumeClaimTemplate options into 
values.persistence configuraion.
fixes #32 
> Persistence config

- README.md
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Fix typo of repo name in the  README
[List any issues this PR will resolve]
> Fix typo of repo name in the  README

- .gitmodules
Signed-off-by: saravanan palanisamy <saravanan30erd@gmail.com>
#71 
> add pointer for ansible-playbook

- .github/CODEOWNERS
- MAINTAINERS.md
Updating the MAINTAINERS and CODEOWNERS file
Closes #111 
> Updating the MAINTAINERS and CODEOWNERS file

- MAINTAINERS.md
Updating the GitHub id in MAINTAINERS file
> Updating the GitHub ID in MAINTAINERS file

- nightly-playground/package-lock.json
- nightly-playground/package.json
- nightly-playground/test/nightly-playground.test.ts
Fix protocol mapping with certificate https://github.com/opensearch-project/opensearch-devops/actions/runs/8285762159
Also adds test cases for expected behavior. 
> Fix protocol mapping with certificate

- .github/workflows/deploy-nightly-playground.yml
Remove bootstrap as it is one time activity. Bootstrap is only required during the start of the activity.
> Remove bootstrap as it is one time activity

- .github/workflows/deploy-nightly-playground.yml
Bump nightly playground with version 2.14.0
> Bump nightly playground with version 2.14.0

- .github/workflows/nightly-playground-trigger.yml
Fix reusable workflow name. Renamed few workflows and forgot to change it in child workflows. This PR fixes it.
> Fix reusable workflow name

- .github/workflows/nightly-playground-deploy.yml
Fix missing quotes
Failing workflow https://github.com/opensearch-project/opensearch-devops/actions/runs/8639723305/job/23687296376
> Fix missing quotes

- .github/workflows/nightly-playground-deploy.yml
> Fix quotes for outputs

- nightly-playground/lib/routing.ts
- nightly-playground/resources/assets/ngnix-index.html
Add customized home page with hyperlinks to 2x and 3x nightly playground
> Add customized home page

- .github/workflows/nightly-playground-deploy.yml
Add workflow step to add sample data by default too all the nightly playgrounds using global tenant
> Add sample data

- .github/workflows/nightly-playground-deploy.yml
- .github/workflows/nightly-playground-trigger.yml
- nightly-playground/lib/nightly-playground-stack.ts
- nightly-playground/lib/routing.ts
- nightly-playground/lib/waf.ts
- nightly-playground/test/nightly-playground.test.ts
Refactor waf and deployment workflow
> Refactor waf and deployment workflow

- .github/workflows/nightly-playground-deploy.yml
Fixes the array index. Currently it gets `None`
> Set array index 0 to get endpoint

- .github/workflows/nightly-playground-deploy.yml
Since we are only deploying infra stack via workflows, the change set in this PR are not required and are proving to be a blocker. GitHub detects the endpoint as a secret and hides the value sending null to the `outputs`
> Remove non-essential context variables

- .github/workflows/nightly-playground-deploy.yml
Missed the checkout step that is required to find the monitor config files. 
#132 
> Add checkout step for adding monitors

- nightly-playground/resources/monitors-config/cluster_health_monitor.json
- nightly-playground/resources/monitors-config/jvm_monitor.json
- nightly-playground/resources/monitors-config/node_monitor.json
Refactor severity and interval for monitors. Changed cluster health interval to 10min and severity to 2/3
> Refactor severity and interval for monitors

- .github/CODEOWNERS
- MAINTAINERS.md
Remove maintainer access for @bbarani 
NA
> Remove maintainer access for @bbarani 

- .github/workflows/nightly-playground-trigger.yml
> Bump 2x to 2.15.0

- .github/workflows/nightly-playground-trigger.yml
> Bump 2x to 2.16

- .github/workflows/nightly-playground-deploy.yml
Add openid client secret to deployment workflow
#192 
> Add openid client secret to deployment workflow

- .github/workflows/nightly-playground-trigger.yml
Bump nightly playground version to 2.19
> Bump nightly playground version to 2.19

- .github/workflows/nightly-playground-trigger.yml
> Bump 2.19.0 to 2.19.1

- .github/workflows/nightly-playground-trigger.yml
Bump nightly playground versions
> Bump nightly playground versions

- .github/workflows/nightly-playground-trigger.yml
> Bump nightly to 3.2.0

- .github/workflows/nightly-playground-deploy.yml
Fix validation and enable sample data for private tenant
> Fix validation and enable sample data for private tenant

- .github/workflows/nightly-playground-deploy.yml
- .github/workflows/nightly-playground-trigger.yml
Add search relevance data for 3.x versions only
https://github.com/opensearch-project/opensearch-devops/issues/214
> Add search relevance data for 3.x versions only
